version: "3.8"
services:
  pihole:
    image: pihole/pihole:${PIHOLE_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_pihole
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
      - CAP_SYS_NICE
      - CAP_SYS_TIME

    environment:
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - FTLCONF_webserver_port=${WEB_PORT:-8080}
      - TZ=${TZ:-UTC}
    volumes:
      - pihole-data:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    network_mode: host
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

   
volumes:
  pihole-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PIHOLE_DATA_VOLUME_PATH}"

  pihole-dnsmasq:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PIHOLE_DNSMASQ_VOLUME_PATH}"
