version: "3"

services:
  ovh-dyndns-client:
    image: cibrandocampo/ovh-dyndns-client:${DOCKER_OVH_VERSION:-stable}
    container_name: ${COMPOSE_PROJECT_NAME}_dyndns-client
    restart: always
    env_file:
      - .env
    networks:
      - dyndns
    volumes:
      - ovh-hosts-config:/app/hosts.json

volumes:
  ovh-hosts-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOSTS_CONFIG_FILE_PATH}"

networks:
  dyndns:
    driver: bridge
